### ISSUE TITLE
BUG - Index creation failed

### ISSUE THREAD

**Issue by toi500** [HonzaTuron/pinecone#4]
I am getting this error:

> 2024-03-05T23:11:23.573Z Index creation failed: HTTPSConnectionPool(host='controller.us-west-2.pinecone.io', port=443): Max retries exceeded with url: /databases (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7efcb138d710>: Failed to establish a new connection: [Errno -2] Name or service not known'))

Can u please help to fix it?

<img width="1459" alt="Screenshot 2024-03-06 002437" src="https://github.com/HonzaTuron/pinecone/assets/138339291/74433fe7-d6d7-4a5b-bca2-a5b5d82606d9">

**Comment by HonzaTuron** [comment]
Hello, would you try again? Seems there was some Pinecone outage: https://status.pinecone.io/

**Comment by toi500** [comment]
I have checked several times today and I am getting the same error.

I have tried everything. Different API Keys, fields, index names but i got the same error over and over.

I am able to load data to Pinecode from the dataset itself via API / GET with no problem.

Here is my config.

<img width="575" alt="V5HZWRAbHPRApXLRn-Screenshot_2024-03-06_114709" src="https://github.com/HonzaTuron/pinecone/assets/138339291/45c486d6-6851-420f-b615-1d07a8489d6d">

**Comment by toi500** [comment]
OK, I figured out what the issue is.

This integration is not ready for Pinacone Serveless indexes, which is the whole point to use Pinacone now as it is 50x cheaper that a pod.

It only works with PODs.

Can you please update the integration at your best convenient? 

<img width="551" alt="Screenshot 2024-03-06 175116" src="https://github.com/HonzaTuron/pinecone/assets/138339291/5e552dcd-308a-4586-b54a-99969815a2a7">

**Comment by HonzaTuron** [comment]
Thank you, will take a look during this week to support serverless indexes as well.

**Comment by HonzaTuron** [comment]
@toi500 Hello, just released a new version of an integration. Feel free to check it and let me know if you find something inconvenient.

**Comment by toi500** [comment]
@HonzaTuron 

I have been checked this for 2 hours now and it looks like that there is some sort of error when the actor tries to load data from the dataset.


<img width="861" alt="Screenshot 2024-03-21 152911" src="https://github.com/HonzaTuron/pinecone/assets/138339291/f46c4565-95dd-4d7c-8c57-93fca55d2917">


I have tried to test different fields but i got the same result. I also checked that the dataset had the fields that I set in the integration.


![Screenshot 2024-03-21 152634](https://github.com/HonzaTuron/pinecone/assets/138339291/c290f370-03a2-4fa3-87b3-fe73d0a603b9)

**Comment by HonzaTuron** [comment]
@toi500 Just released new version, you can try again.

**Comment by toi500** [comment]
@HonzaTuron 

It looks like there is a problem with capturing the credentials from OpenAI now. Also, according with the log there is only loading data from the "url" field even when I set up "url" and "text"

![Screenshot 2024-03-21 155748](https://github.com/HonzaTuron/pinecone/assets/138339291/28cd4396-25b5-48a9-ab24-e09756d6ace8)

I have checked several times and the api key from OpenAI is correct

![Screenshot 2024-03-21 155925](https://github.com/HonzaTuron/pinecone/assets/138339291/276e126f-2423-48cf-8960-ab2e2a0ba1d3)

**Comment by HonzaTuron** [comment]
Yeah it seems OpenAI token wasn't passed correctly in integration side with new release. You can try again as I built new version.

**Comment by toi500** [comment]
it is working now BUT i am facing two unexpected problems:

1) The actor is running for ever (still running)
<img width="611" alt="Screenshot 2024-03-21 165502" src="https://github.com/HonzaTuron/pinecone/assets/138339291/1c1cfec6-b0f7-4955-ab0d-043d3d9881eb">

and

2) The data did not upsert correctly. The url field is missing:

<img width="723" alt="Screenshot 2024-03-21 165625" src="https://github.com/HonzaTuron/pinecone/assets/138339291/9d3e3250-6036-4af9-b9b4-b72fca9d1b8c">

I had to abort it.

<img width="550" alt="Screenshot 2024-03-21 170758" src="https://github.com/HonzaTuron/pinecone/assets/138339291/6a081ce6-bdc5-4fe4-b1c8-11877dd79ebd">

**Comment by HonzaTuron** [comment]
Issue with Actor exiting addressed. Regarding your 2nd issue, try to add `url` field to `metadata_fields` instead.

**Comment by toi500** [comment]
Yes, I got 1 successful run under that strict set up, using TEXT as field and URL as metadata.

--

I have also noted that the TEXT field has to be hard coded somewhere since the Actor is upsetting the data correctly but with the wrong tag.

Here, I put URL as Field and as you can see it is showing the correct url value but under the TEXT tag.

<img width="698" alt="Screenshot 2024-03-21 212457" src="https://github.com/HonzaTuron/pinecone/assets/138339291/a8e1742c-d111-40d5-965b-85853fc26a85">

--

The entries "Field" and "Metadata" in the Actor are confusing since Pinecone uses what they call key:value pairs so whatever you upsert in there it is going to be a "metadata" for them.

The best approach would be to rename the FIELD entry with METADATA as it is the nomenclature that Pinecone is using for their key:value pairs. 

1) If empty, the Actor upsert all the data from the dataset as metadata.

2) The end user can filter it down by inputting the values they want.

**Comment by toi500** [comment]
@HonzaTuron 

I have been checking the code (not my expertise) but I think that there is an issue in this loop that causes that only 1 Field is loaded:

![Screenshot 2024-03-22 171816](https://github.com/HonzaTuron/pinecone/assets/138339291/5186450d-bf31-40c8-ab72-e8c5ffadb94d)


The loop creates a separate ApifyDatasetLoader for each field. Inside the loop, the datasetMappingFunction constructs a Document object. But, the metadata section only processes one field from metadata_fields using getNestedValue.

So, maybe something like this?

![Screenshot 2024-03-22 172931](https://github.com/HonzaTuron/pinecone/assets/138339291/fc52effa-432c-4996-988b-8695a88a2666)

**Comment by HonzaTuron** [comment]
@toi500 Thanks for your feedback. Will take a look tomorrow :)

**Comment by HonzaTuron** [comment]
@toi500 So I guess you can setup one field to be passed in `fields` and rest of the fields as `metadata_fields` then? Wouldn't it do the trick?

**Comment by toi500** [comment]
Well, not really since you only can pass TEXT as field. Whatever other field you put in there is going to be hard tagged as TEXT as I explained you before. 

<img width="698" alt="Screenshot 2024-03-21 212457" src="https://github.com/HonzaTuron/pinecone/assets/138339291/a8e1742c-d111-40d5-965b-85853fc26a85">
..

If u dont want to fix the loop, the best solution would be to make Fields optional or **remove it for good** and let us to set up what metadata we want to upsert to Pinecone. 

That would work.

**Comment by HonzaTuron** [comment]
Okay, just released new version with optional fields. Not sure if framework I'm working with supports empty text though. Please let me know once you try :) 

Also, do I undestand correctly 'text' field is messing up your data?

**Comment by toi500** [comment]
@HonzaTuron

it is spiting this error with the last version:

![Screenshot 2024-03-25 193021](https://github.com/HonzaTuron/pinecone/assets/138339291/1a8cfb55-5e52-4a75-b182-6412ac59d11f)

About the `text` field, your 0.0.57 version upserts only 1 field from the dataset (even if you enter 10) and for some reason it tagged as text even if you put in there `url`. 

But I am pretty sure that this `text` key will be another one if the testing datasets were scrapped from another Actor. We are using the Website Content Crawler one to text Apify. We just need a production ready tool to upsert data to Pinecone to feed LLM apps for our company.

**Comment by HonzaTuron** [comment]
I see, I'm not that advanced Pinecone user, your feedback is very valuable. Just released new version which should fix errors you sent. Also tried to hide default 'text' field.

**Comment by toi500** [comment]
@HonzaTuron 
Dont worry my friend, I am happy to help. In fact, I am mastering Apify and Pinecone with all those testing :)

Please, bear with me 1 min:

The last version 0.059 does not work. It gives you a success run but no data is upserted to Pinacone. I have tried all the possibles set ups (using `fields`, `metadata`, both) and it does not work.

![Screenshot 2024-03-26 020849](https://github.com/HonzaTuron/pinecone/assets/138339291/9ee37cd3-23e9-4e78-a160-fcbc38267cc7)


I propose you the following:

1) Lets give a last try and see if we can fix the last version 0.0.59 and know why is not upserting data. And, if it does not work:

2) Lets roll back to the version 0.0.57

I have been testing this thing A LOT in order to know what the hell is going on and it turned out that the "hard tagging" of the "text" `field` is something that it is coming from Pinecone itself. So, or it is mandatory or it is bugged.

So the version 0.0.57 it is the best we can accomplish here right now. You can even make the text `field` mandatory and explain in the integration that any other data needs to be done via metadata. I know the trick of the version 0.0.57 but you know, it would be good also for other users.

**Comment by HonzaTuron** [comment]
@toi500 In that case I'm out of ideas and releasing 0.0.60 as copy of 0.0.57 as text is mandatory field. Closing this one, feel free to open new issue if you come up with some bug or idea :) Also you can reach me out on Apify Discord.

**Comment by toi500** [comment]
Thank you for your help. I really appreciate your time here.

I let 2 captures with the correct set up in the integration and the final result:

1) Set up on the Pinacone Integration Actor at Apify
--
![Screenshot 2024-03-26 130640](https://github.com/HonzaTuron/pinecone/assets/138339291/821706f1-7884-49ab-b082-123921ad2870)

2) Final result on Pinecone
--
![Screenshot 2024-03-26 131751](https://github.com/HonzaTuron/pinecone/assets/138339291/b18fa18e-20d4-4a97-83d4-8273131bfa8b)
