### ISSUE TITLE
Index creation failed - invalid vector dimension

### ISSUE THREAD

**Issue by ianpoley** [HonzaTuron/pinecone#7]
I'm receiving the following error:
> Index creation failed: PineconeBadRequestError: Vector dimension 1536 does not match the dimension of the index 512

Is it possible to modify the default vector dimension value within the Actor configuration?

**Comment by jirispilka** [comment]
Hi, thank you for your interest in the Pinecone integration!

The current version does not support different embedding models but we are working on the changes that should be released next week (June 10th, 2024).

I will keep this issue open and will post updates here. 

Thank you

**Comment by jirispilka** [comment]
@ianpoley Here is a new [pinecone integration](https://apify.com/apify/pinecone-integration). You should be able to change the embedding model now.
