### ISSUE TITLE
Change emddings model on apify?

### ISSUE THREAD

**Issue by DialogIntelligens** [HonzaTuron/pinecone#8]
How do i change the embeddings model from the standard ada? On apify?

**Comment by jirispilka** [comment]
Hi, thank you for the interest in the Pinecone integration.
Please refer to this [issue](https://github.com/HonzaTuron/pinecone/issues/7#issuecomment-2151538493).
A new version should be released next week.

I will leave this issue open, will update it once released.
Thank you.

**Comment by jirispilka** [comment]
@DialogIntelligens Here is a new [pinecone integration](https://apify.com/apify/pinecone-integration). There was one issue, which has been already fixed. You should be able to change the embedding model now.

Thank you.
